### ISSUE TITLE
Integrating Superuser app breaks Dirty Unicorns 10/mm build

### ISSUE THREAD

**Issue by Thrilleratplay** [seSuperuser/Superuser#11]
After adding seSuperuser/Superuser and seSuperuser/Widgets to my local_manifests, the build fails.  I am not a C developer and am not familiar with compiler different nuances but the best I can determine is that Clang is throwing the errors because nested functions are only supported by GCC.  Any suggestions?

[superuser-du-build-errors.txt](https://github.com/seSuperuser/Superuser/files/211964/superuser-du-build-errors.txt)

Dirty Unicorns is ASOP based.  I added the prebuilt superuser.zip image to the build script and it works perfectly.  I would prefer to compile Superuser with the rest of the build.

**Comment by Thrilleratplay** [comment]
I moved the nested callback functions and used variables in daemon.c and bind.c out of the functions they were defined.  The build was able to complete without an issue but su nor Superuser were found by apps looking for ACCESS_SUPERUSER.  

Is this project still able to be embedded into AOSP Marshmallow ROM builds? Or to be systemless, does it need to be prebuilt and added as a separate zip install?

**Comment by lbdroid** [comment]
ACCESS_SUPERUSER would be a permission declared in the Android manifest. It was never widely supported, and is considered wholly obsolete.

Whether it is embedded in the build or added in afterwards makes no technical difference in the result at all.

**Comment by ikalkov** [comment]
@Thrilleratplay, I have the same issue with my AOSP build. Maybe you can publish your code or create a pull request? It would be nice if I can avoid creating another fork and doing the same work again.

BTW: My platform is running on an embedded board without a recovery. Is there still a way to include a prebuilt binaries during the platform compilation? Thanks!

**Comment by Thrilleratplay** [comment]
@lbdroid Thank you for the info.  I will look into this a bit more over the weekend.

@ikalkov I pushed the changes to a branch called '[unnest](https://github.com/Thrilleratplay/Superuser/tree/unnest)' however I feel a pull request is premature.  I cannot verify the changes I made actually work and it is a bit hacky at the moment so it should be cleaned up.

To answer your question, yes.  I'm not an expert in this but I can at least point you in the right direction.  If you want include APKs, that can just be the addition of the apk and a Android.mk under the vendor of the platform you are building.  Here is an [example](https://github.com/Thrilleratplay/vendor_extra/blob/DU-10.x_MM/prebuilt/common/apk/Android.mk).  Some builds have a link to `vendor/extra/product.mk` under `vendor/ROM_NAME_HERE/config/common.mk` which lets you extend their vendor repo without the need to maintain a fork.  If you want to add a zip file to be installed with the rest of the rom, which I am guessing you are looking for, you need modify the build repo.  [DU installs the SuperSU zip by default](https://github.com/DirtyUnicorns/android_build/blob/m/tools/releasetools/ota_from_target_files.py#L745) and I piggy back on that except replace it with Superuser.zip.  This will vary depending on which platform you are using.  

If the embedded board you are using doesn't have a recovery mode, how are you installing the compile ROM?  If you `adb sideload` the ROM's zip, you should be able to do the same for Superuser.zip

**Comment by ikalkov** [comment]
@Thrilleratplay I actually do know how to include prebuilt apk files into the ROM, but I keep failing on the su binary. It seems to get included correctly, but nothing happens if I try to execute it at runtime. Not even a logcat message is printed. Just silence. I get the same result if I include both (apk and su) into the source tree and build them inline. I suppose there is something wrong with my sepolicy, but setting the whole thing to permissive and removing all "dontaudit's" gave me nothing. Right now I'm running out of ideas, so I was hoping I can include a compiled zip and Android will unpack it during the first boot and take care of required permissions. But that seems to be the wrong way too. The script you pointed me to builds a OTA package which probably needs to be flashed using recovery. For our hardware we rather create separate images (system / userdata / boot / ...) and flash them separately to an external mmc device.

Anyways, thanks for your code. I'll try to use your new branch in the next days and check if the app (and the binary) is working.

**Comment by lbdroid** [comment]
@ikalkov : for the su command to run, does require other changes to be made to the source tree. For instance, it has to be executed by a startup script, and it has to have the correct context applied.

Please see https://github.com/seSuperuser/AOSP-SU-PATCH/blob/master/system_core.patch

Also note that the su binary and the application need to match on their package name.

If you are still having trouble, you should examine logcat and kmsg for explanation.

I do NOT suggest doing something hackish, like adding a separate update.zip to the update.zip.

**Comment by ikalkov** [comment]
@lbdroid : I agree. Adding binary files is in general a poor idea. Thanks for the hint about the correct context. I'll check that. I assumed the build process will automatically assign the correct context if I'm building the image from source. As far as I know, execution from a startup script is only needed if the app is embedded into the settings. WelI, I can at least try it.

I would love to examine logcat and kmsg, but there is nothing... Not a single line gets printed when I try to su.

**Comment by lbdroid** [comment]
Not correct. It absolutely always needs to be run from startup script. This is because the only part of the system where user substitution will be respected by the kernel, is init.

The issue comes from here;
https://github.com/android/platform_frameworks_base/blob/master/cmds/app_process/app_main.cpp -- look at line 188. What that line does is effectively cause the kernel, for that process and every process it spawns (all of them), to ignore setuid.

The su binary, when run from init, is not a child of zygote. It starts in daemon mode, and listens for connections from the client. When from userspace, you run su, THAT process connects to the su daemon. The su client does not actually substitute user.

Now in theory, you could scratch out that line from zygote (since you are running your own builds), but doing so is an unnecessary compromise.

**Comment by ikalkov** [comment]
@lbdroid Thanks a lot for you help, I figured it out now. There were multiple issues with the sepolicy and missing executable flag for the su binary for all users. Working like a charm now!

**Comment by Thrilleratplay** [comment]
My remaining issues were caused by the Superuser makefile and build out directory mismatch.  For the time being, I added copying of init.superuser.rc and linking /sbin/su -> /system/xbin/su to my vendor script.  I'll work on a more elegant solution when I have more time to look into it.

I'm going to close this issue but I am not sure if I should submit a pull request for the changes I made (compile with clang)[thrilleratplay/Superuser@d5e5c1baae0eca932746e4a09e2cb3a572c97c6a].
